# Generated by Django 2.1.2 on 2018-10-26 02:20

import apps.compressor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlinkmodel',
            name='internal',
            field=models.CharField(default=apps.compressor.models.generate_internal_id, editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='hyperlinkmodel',
            name='original',
            field=models.URLField(max_length=254),
        ),
    ]
