# Generated by Django 2.1.2 on 2018-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0002_auto_20181025_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlinkmodel',
            name='original',
            field=models.URLField(max_length=255),
        ),
    ]
